'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { AppShell } from '@/components/AppShell'
import { ArrowLeft, Mail, Phone, Plus, Pencil, Instagram, Facebook, MessageCircle, ShoppingBag, Music2, StickyNote, Clock3, Trash2, Building2 } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Contact={id:string;workspace_id:string;company_id:string|null;first_name:string;last_name:string|null;email:string|null;phone:string|null;job_title:string|null;lifecycle_stage:string;source:string|null;last_interaction_at:string|null;created_at:string}
type Company={id:string;name:string}
type Channel={id:string;channel:string;handle:string|null;external_user_id:string|null;is_primary:boolean}
type Note={id:string;body:string;created_at:string}
type Activity={id:string;activity_type:string;title:string|null;description:string|null;channel:string|null;occurred_at:string}
const channels=['instagram','facebook','whatsapp','mercadolibre','tiktok','email','phone']

export default function ContactDetail(){
 const {id}=useParams<{id:string}>()
 const [contact,setContact]=useState<Contact|null>(null); const [companies,setCompanies]=useState<Company[]>([]); const [channelRows,setChannelRows]=useState<Channel[]>([]); const [notes,setNotes]=useState<Note[]>([]); const [activities,setActivities]=useState<Activity[]>([])
 const [edit,setEdit]=useState(false); const [channelOpen,setChannelOpen]=useState(false); const [noteText,setNoteText]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
 const [form,setForm]=useState({first_name:'',last_name:'',email:'',phone:'',job_title:'',source:'manual',lifecycle_stage:'lead',company_id:''})
 const [channelForm,setChannelForm]=useState({channel:'instagram',handle:'',external_user_id:'',is_primary:false})

 async function load(){
  const {data:c,error}=await supabase.from('contacts').select('id,workspace_id,company_id,first_name,last_name,email,phone,job_title,lifecycle_stage,source,last_interaction_at,created_at').eq('id',id).single()
  if(error||!c){setError(error?.message||'Contacto no encontrado');return}
  setContact(c as Contact); setForm({first_name:c.first_name,last_name:c.last_name||'',email:c.email||'',phone:c.phone||'',job_title:c.job_title||'',source:c.source||'manual',lifecycle_stage:c.lifecycle_stage||'lead',company_id:c.company_id||''})
  const [{data:co},{data:ch},{data:n},{data:a}]=await Promise.all([
   supabase.from('companies').select('id,name').eq('workspace_id',c.workspace_id).order('name'),
   supabase.from('contact_channels').select('id,channel,handle,external_user_id,is_primary').eq('contact_id',id).order('is_primary',{ascending:false}),
   supabase.from('notes').select('id,body,created_at').eq('contact_id',id).order('created_at',{ascending:false}),
   supabase.from('activities').select('id,activity_type,title,description,channel,occurred_at').eq('contact_id',id).order('occurred_at',{ascending:false}).limit(30)
  ])
  setCompanies((co||[]) as Company[]);setChannelRows((ch||[]) as Channel[]);setNotes((n||[]) as Note[]);setActivities((a||[]) as Activity[])
 }
 useEffect(()=>{load()},[id])
 async function save(e:FormEvent){e.preventDefault();if(!contact)return;setBusy(true);setError('');const {error}=await supabase.from('contacts').update({...form,company_id:form.company_id||null,last_name:form.last_name||null,email:form.email||null,phone:form.phone||null,job_title:form.job_title||null}).eq('id',contact.id);if(error)setError(error.message);else{setEdit(false);await load()}setBusy(false)}
 async function updateCompany(companyId:string){if(!contact)return;setBusy(true);setError('');const {error}=await supabase.from('contacts').update({company_id:companyId||null}).eq('id',contact.id).eq('workspace_id',contact.workspace_id);if(error)setError(error.message);else await load();setBusy(false)}
 async function addChannel(e:FormEvent){e.preventDefault();if(!contact)return;setBusy(true);setError('');const {error}=await supabase.from('contact_channels').insert({workspace_id:contact.workspace_id,contact_id:contact.id,channel:channelForm.channel,handle:channelForm.handle||null,external_user_id:channelForm.external_user_id||null,is_primary:channelForm.is_primary});if(error)setError(error.message);else{setChannelOpen(false);setChannelForm({channel:'instagram',handle:'',external_user_id:'',is_primary:false});await load()}setBusy(false)}
 async function addNote(e:FormEvent){e.preventDefault();if(!contact||!noteText.trim())return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {error}=await supabase.from('notes').insert({workspace_id:contact.workspace_id,contact_id:contact.id,body:noteText.trim(),created_by:user.id});if(error)setError(error.message);else{setNoteText('');await load()}setBusy(false)}
 async function removeChannel(channelId:string){if(!confirm('¿Eliminar este canal del contacto?'))return;await supabase.from('contact_channels').delete().eq('id',channelId);await load()}
 const company=companies.find(c=>c.id===contact?.company_id)||null
 if(error&&!contact)return <AppShell><div className="page"><div className="error-banner">{error}</div><Link className="secondary inline-link" href="/contacts"><ArrowLeft size={16}/> Volver a contactos</Link></div></AppShell>
 if(!contact)return <AppShell><div className="loading">Cargando contacto…</div></AppShell>
 return <AppShell><div className="page contact-detail"><div className="detail-top"><Link className="back-link" href="/contacts"><ArrowLeft size={16}/> Contactos</Link><button className="secondary" onClick={()=>setEdit(true)}><Pencil size={15}/> Editar</button></div>
 <div className="profile-head"><div className="profile-avatar">{contact.first_name[0]}{contact.last_name?.[0]||''}</div><div><h1>{contact.first_name} {contact.last_name}</h1><p>{contact.job_title||'Sin cargo'} · {labelStage(contact.lifecycle_stage)}</p><div className="profile-contact">{contact.email&&<span><Mail size={14}/>{contact.email}</span>}{contact.phone&&<span><Phone size={14}/>{contact.phone}</span>}{company&&<Link className="inline-link" href={`/companies/${company.id}`}><Building2 size={14}/>{company.name}</Link>}</div></div></div>
 {error&&<div className="error-banner">{error}</div>}
 <div className="detail-grid"><div className="detail-main">
  <section className="panel"><div className="panel-title"><div><h2>Canales e identidades</h2><p>Unificá todos los puntos de contacto de esta persona.</p></div><button className="secondary" onClick={()=>setChannelOpen(true)}><Plus size={15}/> Agregar canal</button></div><div className="channel-list">{channelRows.length===0?<div className="mini-empty">Todavía no hay canales adicionales.</div>:channelRows.map(ch=><div className="channel-row" key={ch.id}><span className={`channel-icon ${ch.channel}`}>{channelIcon(ch.channel)}</span><div><strong>{labelChannel(ch.channel)}</strong><span>{ch.handle||ch.external_user_id||'Sin identificador visible'}</span></div>{ch.is_primary&&<b className="badge">Principal</b>}<button className="ghost-danger" onClick={()=>removeChannel(ch.id)} title="Eliminar"><Trash2 size={15}/></button></div>)}</div></section>
  <section className="panel"><div className="panel-title"><div><h2>Actividad</h2><p>Historial comercial y de conversaciones.</p></div></div><div className="timeline">{activities.length===0?<div className="mini-empty">La actividad aparecerá acá cuando Lumo registre mensajes, llamadas, tareas y cambios.</div>:activities.map(a=><div className="timeline-item" key={a.id}><span className="timeline-dot"/><div><strong>{a.title||labelChannel(a.activity_type)}</strong><p>{a.description||a.channel||'Actividad registrada'}</p><small>{new Date(a.occurred_at).toLocaleString('es-AR')}</small></div></div>)}</div></section>
 </div><aside className="detail-side"><section className="panel"><div className="panel-title"><div><h2>Información</h2></div></div><dl className="info-list"><div><dt>Estado</dt><dd>{labelStage(contact.lifecycle_stage)}</dd></div><div><dt>Origen</dt><dd>{labelChannel(contact.source||'manual')}</dd></div><div><dt>Creado</dt><dd>{new Date(contact.created_at).toLocaleDateString('es-AR')}</dd></div><div><dt>Última interacción</dt><dd>{contact.last_interaction_at?new Date(contact.last_interaction_at).toLocaleString('es-AR'):'Sin actividad'}</dd></div></dl></section>
 <section className="panel"><div className="panel-title"><div><h2>Empresa</h2><p>Cuenta comercial asociada.</p></div></div><div className="company-link-card"><div>{company?<><strong>{company.name}</strong><span className="count">Vinculada</span></>:<><strong>Sin empresa</strong><span className="count">Contacto individual</span></>}</div>{company&&<Link href={`/companies/${company.id}`}>Ver empresa</Link>}</div><select className="company-select" value={contact.company_id||''} onChange={e=>updateCompany(e.target.value)} disabled={busy}><option value="">Sin empresa</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></section>
 <section className="panel"><div className="panel-title"><div><h2>Notas</h2><p>Contexto interno del equipo.</p></div></div><form className="note-form" onSubmit={addNote}><textarea value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="Escribí una nota sobre este contacto..."/><button className="primary" disabled={busy||!noteText.trim()}><StickyNote size={15}/> Agregar nota</button></form><div className="notes-list">{notes.map(n=><div className="note-card" key={n.id}><p>{n.body}</p><small><Clock3 size={12}/>{new Date(n.created_at).toLocaleString('es-AR')}</small></div>)}</div></section></aside></div>
 {edit&&<div className="modal-backdrop" onClick={()=>setEdit(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h2>Editar contacto</h2><p>Actualizá la información principal.</p><form onSubmit={save}><div className="form2"><label>Nombre<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Apellido<input value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label></div><label>Cargo<input value={form.job_title} onChange={e=>setForm({...form,job_title:e.target.value})}/></label><label>Empresa<select value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})}><option value="">Sin empresa</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Teléfono<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><div className="form2"><label>Origen<select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}>{['manual','instagram','facebook','mercadolibre','whatsapp','tiktok'].map(s=><option key={s} value={s}>{labelChannel(s)}</option>)}</select></label><label>Estado<select value={form.lifecycle_stage} onChange={e=>setForm({...form,lifecycle_stage:e.target.value})}><option value="lead">Lead</option><option value="customer">Cliente</option><option value="inactive">Inactivo</option></select></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setEdit(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button></div></form></div></div>}
 {channelOpen&&<div className="modal-backdrop" onClick={()=>setChannelOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h2>Agregar canal</h2><p>Vinculá otra identidad al mismo cliente.</p><form onSubmit={addChannel}><label>Canal<select value={channelForm.channel} onChange={e=>setChannelForm({...channelForm,channel:e.target.value})}>{channels.map(c=><option key={c} value={c}>{labelChannel(c)}</option>)}</select></label><label>Usuario / handle<input placeholder="Ej: @maria o +54 9..." value={channelForm.handle} onChange={e=>setChannelForm({...channelForm,handle:e.target.value})}/></label><label>ID externo (opcional)<input value={channelForm.external_user_id} onChange={e=>setChannelForm({...channelForm,external_user_id:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={channelForm.is_primary} onChange={e=>setChannelForm({...channelForm,is_primary:e.target.checked})}/> Marcar como canal principal</label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setChannelOpen(false)}>Cancelar</button><button className="primary" disabled={busy}>Agregar canal</button></div></form></div></div>}
 </div></AppShell>
}
function labelStage(v:string){return ({lead:'Lead',customer:'Cliente',inactive:'Inactivo'} as Record<string,string>)[v]||v}
function labelChannel(v:string){return ({manual:'Manual',instagram:'Instagram',facebook:'Facebook',mercadolibre:'Mercado Libre',whatsapp:'WhatsApp',tiktok:'TikTok',email:'Email',phone:'Teléfono',message:'Mensaje',call:'Llamada',meeting:'Reunión'} as Record<string,string>)[v]||v}
function channelIcon(v:string){if(v==='instagram')return <Instagram size={16}/>;if(v==='facebook')return <Facebook size={16}/>;if(v==='mercadolibre')return <ShoppingBag size={16}/>;if(v==='tiktok')return <Music2 size={16}/>;if(v==='email')return <Mail size={16}/>;if(v==='phone')return <Phone size={16}/>;return <MessageCircle size={16}/>} 
