'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {AppShell} from '@/components/AppShell'
import {supabase} from '@/lib/supabase'
import {Plus,Play,Pause,Trash2,Zap,CheckCircle2,XCircle,Clock3,Pencil,Copy,FlaskConical} from 'lucide-react'

type Automation={id:string;name:string;description:string|null;status:'draft'|'active'|'paused';trigger_type:string;condition_config:any;action_type:string;action_config:any;last_run_at:string|null;created_at:string}
type Member={user_id:string;role:string;profiles:{full_name:string|null}|null}
type Run={id:string;status:string;executed_at:string;error_message:string|null;automation_id:string;automations:{name:string}|null}
type Condition={field:string;operator:string;value:string}
type Action={type:string;value:string}

const triggerOptions=[['message_received','Llega un mensaje'],['conversation_created','Se crea una conversación'],['conversation_status_changed','Cambia el estado de una conversación'],['opportunity_stage_changed','Cambia una oportunidad de etapa'],['task_created','Se crea una tarea'],['manual','Ejecución manual']]
const actionOptions=[['create_task','Crear tarea'],['set_priority','Cambiar prioridad'],['set_conversation_status','Cambiar estado de conversación'],['assign_conversation','Asignar conversación']]
const fieldOptions:Record<string,string[][]>={
 message_received:[['channel','Canal'],['body','Texto del mensaje'],['intent','Intención detectada'],['confidence','Confianza de inteligencia'],['suggested_priority','Prioridad sugerida'],['status','Estado de conversación'],['priority','Prioridad actual']],
 conversation_created:[['channel','Canal'],['intent','Intención detectada'],['confidence','Confianza de inteligencia'],['suggested_priority','Prioridad sugerida'],['status','Estado'],['priority','Prioridad actual']],
 conversation_status_changed:[['status','Nuevo estado'],['channel','Canal'],['priority','Prioridad']],
 opportunity_stage_changed:[['stage','Etapa'],['source_channel','Canal de origen']],
 task_created:[['priority','Prioridad'],['status','Estado']],manual:[]}
const channelValues=[['instagram','Instagram'],['facebook','Facebook'],['whatsapp','WhatsApp'],['mercadolibre','Mercado Libre'],['tiktok','TikTok']]
const priorityValues=[['low','Baja'],['normal','Normal'],['high','Alta'],['urgent','Urgente']]
const statusValues=[['open','Abierta'],['pending','Pendiente'],['closed','Cerrada']]
const intentValues=[['price','Consulta de precio'],['purchase','Intención de compra'],['shipping','Envío / entrega'],['availability','Stock / disponibilidad'],['complaint','Reclamo / problema'],['payment','Pago / cuotas'],['product','Consulta de producto'],['greeting','Saludo'],['other','Consulta general']]

export default function AutomationsV5(){
 const [workspaceId,setWorkspaceId]=useState<string|null>(null),[userId,setUserId]=useState<string|null>(null)
 const [rows,setRows]=useState<Automation[]>([]),[runs,setRuns]=useState<Run[]>([]),[members,setMembers]=useState<Member[]>([])
 const [open,setOpen]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[triggerType,setTriggerType]=useState('message_received'),[logic,setLogic]=useState<'and'|'or'>('and')
 const [conditions,setConditions]=useState<Condition[]>([{field:'intent',operator:'equals',value:'purchase'}]),[actions,setActions]=useState<Action[]>([{type:'set_priority',value:'high'}])
 const [testRow,setTestRow]=useState<Automation|null>(null),[testPayload,setTestPayload]=useState<Record<string,string>>({}),[testResult,setTestResult]=useState<any>(null)

 useEffect(()=>{bootstrap()},[])
 async function bootstrap(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;setUserId(user.id);const {data:member,error:e}=await supabase.from('workspace_members').select('workspace_id').eq('user_id',user.id).eq('status','active').limit(1).single();if(e||!member){setError(e?.message||'No encontramos tu espacio de trabajo.');return};setWorkspaceId(member.workspace_id);await Promise.all([load(member.workspace_id),loadRuns(member.workspace_id),loadMembers(member.workspace_id)])}
 async function load(wid=workspaceId){if(!wid)return;const {data,error:e}=await supabase.from('automations').select('id,name,description,status,trigger_type,condition_config,action_type,action_config,last_run_at,created_at').eq('workspace_id',wid).order('created_at',{ascending:false});if(e)setError(e.message);else setRows((data||[]) as Automation[])}
 async function loadRuns(wid=workspaceId){if(!wid)return;const {data}=await supabase.from('automation_runs').select('id,status,executed_at,error_message,automation_id,automations(name)').eq('workspace_id',wid).order('executed_at',{ascending:false}).limit(12);setRuns((data||[]) as unknown as Run[])}
 async function loadMembers(wid=workspaceId){if(!wid)return;const {data}=await supabase.from('workspace_members').select('user_id,role,profiles(full_name)').eq('workspace_id',wid).eq('status','active');setMembers((data||[]) as unknown as Member[])}

 const activeCount=useMemo(()=>rows.filter(r=>r.status==='active').length,[rows])
 const successfulRuns=useMemo(()=>runs.filter(r=>r.status==='success').length,[runs])
 function resetBuilder(){setEditingId(null);setName('');setDescription('');setTriggerType('message_received');setLogic('and');setConditions([{field:'intent',operator:'equals',value:'purchase'}]);setActions([{type:'set_priority',value:'high'}])}
 function openNew(){resetBuilder();setOpen(true);setError('');setSuccess('')}
 function changeTrigger(v:string){setTriggerType(v);const f=(fieldOptions[v]||[])[0]?.[0]||'';setConditions(f?[{field:f,operator:defaultOperator(f),value:defaultValue(f)}]:[])}
 function addCondition(){const f=(fieldOptions[triggerType]||[])[0]?.[0];if(f)setConditions(v=>[...v,{field:f,operator:defaultOperator(f),value:defaultValue(f)}])}
 function edit(row:Automation){const p=parseRule(row);setEditingId(row.id);setName(row.name);setDescription(row.description||'');setTriggerType(row.trigger_type);setLogic(p.logic);setConditions(p.conditions);setActions(p.actions);setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();if(!workspaceId||!userId||!name.trim()||!actions.length)return;setBusy(true);setError('');const payload={name:name.trim(),description:description.trim()||null,trigger_type:triggerType,trigger_config:{},condition_config:conditions.length?{logic,conditions}:{},action_type:actions[0].type,action_config:{actions:actions.map(a=>({type:a.type,config:{value:a.value}}))},updated_at:new Date().toISOString()};const r=editingId?await supabase.from('automations').update(payload).eq('id',editingId).eq('workspace_id',workspaceId):await supabase.from('automations').insert({...payload,workspace_id:workspaceId,status:'draft',created_by:userId});setBusy(false);if(r.error){setError(r.error.message);return};setOpen(false);setSuccess(editingId?'Automatización actualizada.':'Automatización creada como borrador.');resetBuilder();await load(workspaceId)}
 async function duplicate(row:Automation){if(!workspaceId||!userId)return;const {error:e}=await supabase.from('automations').insert({workspace_id:workspaceId,name:`${row.name} · Copia`,description:row.description,status:'draft',trigger_type:row.trigger_type,trigger_config:{},condition_config:row.condition_config||{},action_type:row.action_type,action_config:row.action_config||{},created_by:userId});if(e)setError(e.message);else{setSuccess('Automatización duplicada como borrador.');await load(workspaceId)}}
 async function toggle(row:Automation){if(!workspaceId)return;const next=row.status==='active'?'paused':'active';const {error:e}=await supabase.from('automations').update({status:next,updated_at:new Date().toISOString()}).eq('id',row.id).eq('workspace_id',workspaceId);if(e)setError(e.message);else setRows(v=>v.map(x=>x.id===row.id?{...x,status:next}:x))}
 async function remove(row:Automation){if(!workspaceId||!confirm(`¿Eliminar la automatización “${row.name}”?`))return;const {error:e}=await supabase.from('automations').delete().eq('id',row.id).eq('workspace_id',workspaceId);if(e)setError(e.message);else setRows(v=>v.filter(x=>x.id!==row.id))}
 function openTest(row:Automation){const p=parseRule(row),payload:Record<string,string>={};for(const [f] of fieldOptions[row.trigger_type]||[])payload[f]=defaultTestValue(f);for(const c of p.conditions)payload[c.field]=c.value||defaultTestValue(c.field);setTestRow(row);setTestPayload(payload);setTestResult(null)}
 function runTest(){if(!testRow)return;const p=parseRule(testRow);const checks=p.conditions.map(c=>({condition:c,actual:testPayload[c.field]||'',matched:match(c,testPayload[c.field]||'')}));const matched=!checks.length||p.logic==='or'?checks.some((x:any)=>x.matched):checks.every((x:any)=>x.matched);setTestResult({matched,checks,actions:p.actions})}

 return <AppShell><div className="page"><div className="page-head"><div><h1>Automatizaciones</h1><p>Reglas operativas conectadas a la inteligencia del Inbox.</p></div><button className="primary compact" onClick={openNew}><Plus size={17}/> Nueva automatización</button></div>
 <div className="test-banner"><strong>WHEN → IF → THEN + Inteligencia</strong><span>Ahora podés decidir usando intención, confianza y prioridad sugerida detectadas en cada mensaje.</span></div>
 {error&&<div className="error-banner">{error}</div>}{success&&<div className="test-banner"><strong>Listo</strong><span>{success}</span></div>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:14,marginBottom:18}}><Metric label="Total" value={rows.length}/><Metric label="Activas" value={activeCount}/><Metric label="Ejecuciones recientes" value={runs.length}/><Metric label="Exitosas" value={successfulRuns}/></div>
 <section className="panel" style={{overflow:'hidden',marginBottom:18}}>{rows.length===0?<div className="empty" style={{padding:48}}><Zap size={30}/><strong>Todavía no hay automatizaciones</strong><span>Creá una regla y activala cuando esté lista.</span></div>:rows.map(row=><div key={row.id} style={{display:'grid',gridTemplateColumns:'minmax(220px,1.4fr) minmax(190px,1fr) 120px 190px',gap:12,alignItems:'center',padding:'16px 18px',borderBottom:'1px solid rgba(15,23,42,.08)'}}><div><strong style={{display:'block'}}>{row.name}</strong><span style={{fontSize:13,opacity:.62}}>{row.description||conditionSummary(row)}</span></div><div><span style={{fontSize:11,fontWeight:700,opacity:.55}}>WHEN</span><div>{labelOf(triggerOptions,row.trigger_type)}</div><small style={{opacity:.6}}>THEN {actionsSummary(row)}</small></div><div><span style={{display:'inline-flex',padding:'6px 9px',borderRadius:999,fontSize:12,fontWeight:700,background:row.status==='active'?'rgba(22,163,74,.10)':'rgba(100,116,139,.10)'}}>{statusLabel(row.status)}</span></div><div style={{display:'flex',gap:6,justifyContent:'flex-end'}}><button className="iconbtn" title="Probar" onClick={()=>openTest(row)}><FlaskConical size={15}/></button><button className="iconbtn" title="Editar" onClick={()=>edit(row)}><Pencil size={15}/></button><button className="iconbtn" title="Duplicar" onClick={()=>duplicate(row)}><Copy size={15}/></button><button className="iconbtn" title={row.status==='active'?'Pausar':'Activar'} onClick={()=>toggle(row)}>{row.status==='active'?<Pause size={15}/>:<Play size={15}/>}</button><button className="iconbtn" title="Eliminar" onClick={()=>remove(row)}><Trash2 size={15}/></button></div></div>)}</section>
 <section className="panel"><div style={{padding:'17px 18px',borderBottom:'1px solid rgba(15,23,42,.08)'}}><strong>Historial de ejecuciones</strong></div>{runs.length===0?<div className="mini-empty" style={{padding:30}}>Todavía no hay ejecuciones.</div>:runs.map(run=><div key={run.id} style={{display:'grid',gridTemplateColumns:'30px minmax(220px,1fr) 130px',gap:10,padding:'13px 18px',borderBottom:'1px solid rgba(15,23,42,.06)'}}><div>{run.status==='success'?<CheckCircle2 size={18}/>:run.status==='failed'?<XCircle size={18}/>:<Clock3 size={18}/>}</div><div><strong>{run.automations?.name||'Automatización'}</strong>{run.error_message&&<small style={{display:'block',opacity:.6}}>{run.error_message}</small>}</div><small>{formatDate(run.executed_at)}</small></div>)}</section>
 {open&&<div className="modal-backdrop"><div className="modal" style={{maxWidth:860,maxHeight:'90vh',overflow:'auto'}}><div className="modal-head"><div><h2>{editingId?'Editar automatización':'Nueva automatización'}</h2><p>Podés combinar señales del Inbox con AND / OR.</p></div><button className="iconbtn" onClick={()=>{setOpen(false);resetBuilder()}}>×</button></div><form onSubmit={save} className="form-grid"><label className="full">Nombre<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Priorizar intención de compra"/></label><label className="full">Descripción<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Opcional"/></label><label className="full"><strong>WHEN</strong> — Cuando<select value={triggerType} onChange={e=>changeTrigger(e.target.value)}>{triggerOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{(fieldOptions[triggerType]||[]).length>0&&<div className="full" style={{display:'flex',flexDirection:'column',gap:9}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>IF — Condiciones</strong><div style={{display:'flex',gap:7}}><select value={logic} onChange={e=>setLogic(e.target.value as any)}><option value="and">TODAS (AND)</option><option value="or">CUALQUIERA (OR)</option></select><button type="button" className="secondary" onClick={addCondition}>+ Condición</button></div></div>{conditions.map((c,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1.1fr .8fr 1fr 42px',gap:8}}><select value={c.field} onChange={e=>{const f=e.target.value;setConditions(v=>v.map((x,j)=>j===i?{field:f,operator:defaultOperator(f),value:defaultValue(f)}:x))}}>{fieldOptions[triggerType].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={c.operator} onChange={e=>setConditions(v=>v.map((x,j)=>j===i?{...x,operator:e.target.value}:x))}>{operatorsFor(c.field).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><ConditionValue condition={c} onChange={value=>setConditions(v=>v.map((x,j)=>j===i?{...x,value}:x))}/><button type="button" className="iconbtn" onClick={()=>setConditions(v=>v.filter((_,j)=>j!==i))}>×</button></div>)}</div>}
 <div className="full" style={{display:'flex',flexDirection:'column',gap:9}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>THEN — Acciones</strong><button type="button" className="secondary" onClick={()=>setActions(v=>[...v,{type:'create_task',value:'Seguimiento'}])}>+ Acción</button></div>{actions.map((a,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1fr 1.4fr 42px',gap:8}}><select value={a.type} onChange={e=>setActions(v=>v.map((x,j)=>j===i?{type:e.target.value,value:defaultActionValue(e.target.value)}:x))}>{actionOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><ActionValue action={a} members={members} onChange={value=>setActions(v=>v.map((x,j)=>j===i?{...x,value}:x))}/><button type="button" className="iconbtn" onClick={()=>setActions(v=>v.filter((_,j)=>j!==i))}>×</button></div>)}</div><div className="modal-actions full"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':editingId?'Guardar cambios':'Crear borrador'}</button></div></form></div></div>}
 {testRow&&<div className="modal-backdrop"><div className="modal" style={{maxWidth:760}}><div className="modal-head"><div><h2>Probar automatización</h2><p>Simulación segura: no modifica datos.</p></div><button className="iconbtn" onClick={()=>setTestRow(null)}>×</button></div><div style={{display:'grid',gap:9}}>{Object.keys(testPayload).map(f=><label key={f}>{fieldLabel(f)}<input value={testPayload[f]} onChange={e=>setTestPayload(v=>({...v,[f]:e.target.value}))}/></label>)}</div><div className="modal-actions"><button className="secondary" onClick={()=>setTestRow(null)}>Cerrar</button><button className="primary" onClick={runTest}><FlaskConical size={15}/> Ejecutar prueba</button></div>{testResult&&<div className="panel" style={{padding:14,marginTop:12}}><strong>{testResult.matched?'La regla CUMPLE':'La regla NO CUMPLE'}</strong>{testResult.checks.map((x:any,i:number)=><div key={i} style={{fontSize:13,marginTop:7}}>{x.matched?'✓':'×'} {fieldLabel(x.condition.field)} {operatorLabel(x.condition.operator)} “{x.condition.value}” · recibido “{x.actual}”</div>)}{testResult.matched&&<div style={{marginTop:10,fontSize:13}}>Ejecutaría: {testResult.actions.map((a:Action)=>labelOf(actionOptions,a.type)).join(' → ')}</div>}</div>}</div></div>}
 </div></AppShell>
}

function ConditionValue({condition,onChange}:{condition:Condition;onChange:(v:string)=>void}){if(condition.field==='channel')return <select value={condition.value} onChange={e=>onChange(e.target.value)}>{channelValues.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>;if(condition.field==='intent')return <select value={condition.value} onChange={e=>onChange(e.target.value)}>{intentValues.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>;if(condition.field==='suggested_priority'||condition.field==='priority')return <select value={condition.value} onChange={e=>onChange(e.target.value)}>{priorityValues.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>;if(condition.field==='status')return <select value={condition.value} onChange={e=>onChange(e.target.value)}>{statusValues.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>;if(condition.field==='confidence')return <input type="number" min="0" max="1" step="0.05" value={condition.value} onChange={e=>onChange(e.target.value)}/>;return <input value={condition.value} onChange={e=>onChange(e.target.value)}/>}
function ActionValue({action,members,onChange}:{action:Action;members:Member[];onChange:(v:string)=>void}){if(action.type==='set_priority')return <select value={action.value} onChange={e=>onChange(e.target.value)}>{priorityValues.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>;if(action.type==='set_conversation_status')return <select value={action.value} onChange={e=>onChange(e.target.value)}>{statusValues.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>;if(action.type==='assign_conversation')return <select value={action.value} onChange={e=>onChange(e.target.value)}><option value="">Elegí una persona</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.profiles?.full_name||'Usuario'} · {m.role}</option>)}</select>;return <input value={action.value} onChange={e=>onChange(e.target.value)} placeholder="Título de la tarea"/>}
function parseRule(row:Automation){const raw=row.condition_config||{},conditions:Condition[]=Array.isArray(raw.conditions)?raw.conditions:(raw.field?[raw]:[]),logic=(raw.logic==='or'?'or':'and') as 'and'|'or';const actions:Action[]=Array.isArray(row.action_config?.actions)?row.action_config.actions.map((a:any)=>({type:a.type,value:String(a.config?.value??'')})):[{type:row.action_type,value:String(row.action_config?.value??'')}];return {conditions,logic,actions}}
function match(c:Condition,actual:string){const a=String(actual??''),e=String(c.value??'');if(['greater_than','greater_or_equal','less_than','less_or_equal'].includes(c.operator)){const an=Number(a),en=Number(e);if(!Number.isFinite(an)||!Number.isFinite(en))return false;if(c.operator==='greater_than')return an>en;if(c.operator==='greater_or_equal')return an>=en;if(c.operator==='less_than')return an<en;return an<=en}const al=a.toLowerCase(),el=e.toLowerCase();if(c.operator==='not_equals')return al!==el;if(c.operator==='contains')return al.includes(el);if(c.operator==='not_contains')return !al.includes(el);return al===el}
function operatorsFor(field:string){return field==='confidence'?[['greater_or_equal','Mayor o igual'],['greater_than','Mayor que'],['less_or_equal','Menor o igual'],['less_than','Menor que'],['equals','Igual']]:field==='body'?[['contains','Contiene'],['not_contains','No contiene'],['equals','Es igual a']]:[['equals','Es igual a'],['not_equals','No es igual a']]}
function defaultOperator(field:string){return field==='body'?'contains':field==='confidence'?'greater_or_equal':'equals'}
function defaultValue(field:string){return field==='channel'?'instagram':field==='intent'?'purchase':field==='confidence'?'0.70':field==='suggested_priority'||field==='priority'?'high':field==='status'?'open':''}
function defaultTestValue(field:string){return field==='channel'?'instagram':field==='intent'?'purchase':field==='confidence'?'0.84':field==='suggested_priority'?'high':field==='priority'?'normal':field==='status'?'open':field==='body'?'Quiero comprar, ¿cuánto sale?':''}
function defaultActionValue(type:string){return type==='set_priority'?'high':type==='set_conversation_status'?'open':type==='create_task'?'Seguimiento comercial':''}
function conditionSummary(row:Automation){const p=parseRule(row);if(!p.conditions.length)return 'Sin condiciones';return p.conditions.map(c=>`${fieldLabel(c.field)} ${operatorLabel(c.operator)} ${valueLabel(c.field,c.value)}`).join(p.logic==='or'?' OR ':' AND ')}
function actionsSummary(row:Automation){return parseRule(row).actions.map(a=>labelOf(actionOptions,a.type)).join(' → ')}
function labelOf(options:string[][],value:string){return options.find(x=>x[0]===value)?.[1]||value}
function fieldLabel(v:string){const all=Object.values(fieldOptions).flat();return all.find(x=>x[0]===v)?.[1]||v}
function operatorLabel(v:string){return ({equals:'=',not_equals:'≠',contains:'contiene',not_contains:'no contiene',greater_than:'>',greater_or_equal:'≥',less_than:'<',less_or_equal:'≤'} as Record<string,string>)[v]||v}
function valueLabel(field:string,v:string){if(field==='intent')return labelOf(intentValues,v);if(field.includes('priority'))return labelOf(priorityValues,v);if(field==='channel')return labelOf(channelValues,v);if(field==='status')return labelOf(statusValues,v);return v}
function statusLabel(v:string){return v==='active'?'Activa':v==='paused'?'Pausada':'Borrador'}
function formatDate(v:string|null){return v?new Date(v).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):''}
function Metric({label,value}:{label:string;value:number}){return <div className="panel" style={{padding:16}}><div style={{fontSize:12,opacity:.58}}>{label}</div><strong style={{fontSize:24}}>{value}</strong></div>}
