'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {AppShell} from '@/components/AppShell'
import {supabase} from '@/lib/supabase'
import {Search,Plus,Send,Instagram,Facebook,MessageCircle,Store,Music2,BadgeDollarSign,RefreshCw,Wifi} from 'lucide-react'

type Contact={id:string;first_name:string;last_name:string|null;email:string|null;phone:string|null;source:string|null}
type Member={user_id:string;role:string;profiles:{full_name:string|null}|null}
type Connection={id:string;channel:string;name:string;settings:any}
type Conversation={id:string;contact_id:string|null;channel_connection_id:string;status:string;priority:string;assigned_user_id:string|null;last_message_at:string|null;unread_count:number;subject:string|null;contacts:Contact|null;channel_connections:Connection|null}
type Message={id:string;conversation_id?:string;direction:string;sender_type:string;body:string|null;sent_at:string;status:string}
type Stage={id:string;name:string;position:number;probability:number;is_won:boolean;is_lost:boolean}
type Preview={body:string|null;sent_at:string;direction:string}
const channels=['instagram','facebook','whatsapp','mercadolibre','tiktok']

export default function InboxV2(){
 const [workspaceId,setWorkspaceId]=useState<string|null>(null),[userId,setUserId]=useState<string|null>(null)
 const [contacts,setContacts]=useState<Contact[]>([]),[members,setMembers]=useState<Member[]>([]),[stages,setStages]=useState<Stage[]>([])
 const [conversations,setConversations]=useState<Conversation[]>([]),[previews,setPreviews]=useState<Record<string,Preview>>({}),[selectedId,setSelectedId]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([])
 const [q,setQ]=useState(''),[statusFilter,setStatusFilter]=useState('open'),[channelFilter,setChannelFilter]=useState('all'),[reply,setReply]=useState('')
 const [openNew,setOpenNew]=useState(false),[openOpp,setOpenOpp]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[live,setLive]=useState(false)
 const [newConv,setNewConv]=useState({contact_id:'',channel:'instagram',message:'Hola, quisiera información sobre un producto.'})
 const [opp,setOpp]=useState({name:'',amount:'',stage_id:'',expected_close_date:''})
 const selected=conversations.find(c=>c.id===selectedId)||null

 async function bootstrap(){
  const {data:{user}}=await supabase.auth.getUser();if(!user)return;setUserId(user.id)
  const {data:mem,error:e}=await supabase.from('workspace_members').select('workspace_id').eq('user_id',user.id).eq('status','active').limit(1).single();if(e||!mem){setError(e?.message||'No encontramos tu espacio de trabajo.');return}
  setWorkspaceId(mem.workspace_id)
  const [{data:cs},{data:ms},{data:ss}]=await Promise.all([
   supabase.from('contacts').select('id,first_name,last_name,email,phone,source').eq('workspace_id',mem.workspace_id).order('first_name'),
   supabase.from('workspace_members').select('user_id,role,profiles(full_name)').eq('workspace_id',mem.workspace_id).eq('status','active'),
   supabase.from('sales_stages').select('id,name,position,probability,is_won,is_lost').eq('workspace_id',mem.workspace_id).order('position')])
  setContacts((cs||[]) as Contact[]);setMembers((ms||[]) as unknown as Member[]);setStages((ss||[]) as Stage[]);await loadConversations(mem.workspace_id)
 }
 async function loadConversations(wid=workspaceId){
  if(!wid)return
  const {data,error:e}=await supabase.from('conversations').select('id,contact_id,channel_connection_id,status,priority,assigned_user_id,last_message_at,unread_count,subject,contacts(id,first_name,last_name,email,phone,source),channel_connections(id,channel,name,settings)').eq('workspace_id',wid).order('last_message_at',{ascending:false,nullsFirst:false})
  if(e){setError(e.message);return}const rows=(data||[]) as unknown as Conversation[];setConversations(rows);if(!selectedId&&rows.length)setSelectedId(rows[0].id);await loadPreviews(rows.map(r=>r.id))
 }
 async function loadPreviews(ids:string[]){if(!ids.length){setPreviews({});return};const {data}=await supabase.from('messages').select('conversation_id,body,sent_at,direction').in('conversation_id',ids).order('sent_at',{ascending:false}).limit(Math.min(ids.length*6,300));const out:Record<string,Preview>={};for(const m of data||[])if(!out[m.conversation_id])out[m.conversation_id]={body:m.body,sent_at:m.sent_at,direction:m.direction};setPreviews(out)}
 async function loadMessages(cid:string){const {data,error:e}=await supabase.from('messages').select('id,conversation_id,direction,sender_type,body,sent_at,status').eq('conversation_id',cid).order('sent_at');if(e)setError(e.message);else setMessages((data||[]) as Message[]);if(workspaceId){await supabase.from('conversations').update({unread_count:0}).eq('id',cid).eq('workspace_id',workspaceId);setConversations(v=>v.map(c=>c.id===cid?{...c,unread_count:0}:c))}}
 useEffect(()=>{bootstrap()},[])
 useEffect(()=>{if(selectedId)loadMessages(selectedId)},[selectedId,workspaceId])
 useEffect(()=>{if(!workspaceId)return;const ch=supabase.channel(`inbox-${workspaceId}`)
  .on('postgres_changes',{event:'*',schema:'public',table:'conversations',filter:`workspace_id=eq.${workspaceId}`},()=>loadConversations(workspaceId))
  .on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`workspace_id=eq.${workspaceId}`},(p:any)=>{const m=p.new as Message;if(m.conversation_id){setPreviews(v=>({...v,[m.conversation_id!]:{body:m.body,sent_at:m.sent_at,direction:m.direction}}));if(m.conversation_id===selectedId)setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,m]);loadConversations(workspaceId)}})
  .subscribe(s=>setLive(s==='SUBSCRIBED'));return()=>{supabase.removeChannel(ch);setLive(false)}},[workspaceId,selectedId])

 const filtered=useMemo(()=>conversations.filter(c=>{const name=c.contacts?`${c.contacts.first_name} ${c.contacts.last_name||''}`:'';const preview=previews[c.id]?.body||'';const channel=c.channel_connections?.channel||'';const text=`${name} ${c.subject||''} ${preview} ${labelChannel(channel)}`.toLowerCase();return text.includes(q.toLowerCase())&&(statusFilter==='all'||c.status===statusFilter)&&(channelFilter==='all'||channel===channelFilter)}),[conversations,previews,q,statusFilter,channelFilter])
 const unreadTotal=conversations.reduce((n,c)=>n+Number(c.unread_count||0),0)

 async function ensureTestConnection(channel:string){if(!workspaceId)throw new Error('Workspace no disponible');const {data:f}=await supabase.from('channel_connections').select('id,channel,name,settings').eq('workspace_id',workspaceId).eq('channel',channel).contains('settings',{mode:'test'}).limit(1);if(f?.length)return f[0] as Connection;const {data,error:e}=await supabase.from('channel_connections').insert({workspace_id:workspaceId,channel,name:`${labelChannel(channel)} · Modo prueba`,status:'connected',settings:{mode:'test'}}).select('id,channel,name,settings').single();if(e)throw e;return data as Connection}
 async function createConversation(e:FormEvent){e.preventDefault();if(!workspaceId||!newConv.contact_id||!newConv.message.trim())return;setBusy(true);setError('');try{const connection=await ensureTestConnection(newConv.channel),now=new Date().toISOString();const {data:conv,error:ce}=await supabase.from('conversations').insert({workspace_id:workspaceId,contact_id:newConv.contact_id,channel_connection_id:connection.id,status:'open',priority:'normal',assigned_user_id:userId,last_message_at:now,last_incoming_at:now,unread_count:1,metadata:{mode:'test'}}).select('id').single();if(ce)throw ce;const {error:me}=await supabase.from('messages').insert({workspace_id:workspaceId,conversation_id:conv.id,direction:'incoming',sender_type:'contact',body:newConv.message,message_type:'text',status:'received',sent_at:now,attachments:[],metadata:{mode:'test'}});if(me)throw me;setOpenNew(false);setNewConv({contact_id:'',channel:'instagram',message:'Hola, quisiera información sobre un producto.'});await loadConversations(workspaceId);setSelectedId(conv.id)}catch(x:any){setError(x.message||'No pudimos crear la conversación')}finally{setBusy(false)}}
 async function sendReply(e:FormEvent){e.preventDefault();if(!workspaceId||!selected||!reply.trim())return;setBusy(true);setError('');const body=reply.trim();try{const liveMeta=selected.channel_connections?.settings?.mode!=='test'&&['instagram','facebook'].includes(selected.channel_connections?.channel||'');if(liveMeta){const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Tu sesión expiró.');const res=await fetch('/api/integrations/meta/send',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({conversation_id:selected.id,body})});const result=await res.json();if(!res.ok)throw new Error(result.error||'No pudimos enviar el mensaje por Meta.');const m=result.message as Message;setMessages(v=>v.some(x=>x.id===m.id)?v:[...v,m]);setReply('')}else{const now=new Date().toISOString();const {data,error:e2}=await supabase.from('messages').insert({workspace_id:workspaceId,conversation_id:selected.id,direction:'outgoing',sender_type:'user',sender_user_id:userId,body,message_type:'text',status:'sent',sent_at:now,attachments:[],metadata:{mode:selected.channel_connections?.settings?.mode||'test'}}).select('id,conversation_id,direction,sender_type,body,sent_at,status').single();if(e2)throw e2;setMessages(v=>[...v,data as Message]);setReply('');await supabase.from('conversations').update({last_message_at:now,last_outgoing_at:now,status:'open'}).eq('id',selected.id)}}catch(x:any){setError(x.message||'No pudimos enviar la respuesta')}finally{setBusy(false)}}
 async function updateConversation(fields:Record<string,any>){if(!selected||!workspaceId)return;const {error:e}=await supabase.from('conversations').update(fields).eq('id',selected.id).eq('workspace_id',workspaceId);if(e)setError(e.message);else setConversations(v=>v.map(c=>c.id===selected.id?{...c,...fields}:c))}
 function startOpportunity(){if(!selected)return;const first=stages.find(s=>!s.is_won&&!s.is_lost)||stages[0],person=selected.contacts?`${selected.contacts.first_name} ${selected.contacts.last_name||''}`.trim():'Cliente';setOpp({name:`Venta - ${person}`,amount:'',stage_id:first?.id||'',expected_close_date:''});setOpenOpp(true)}
 async function createOpportunity(e:FormEvent){e.preventDefault();if(!workspaceId||!userId||!selected||!opp.name.trim()||!opp.stage_id)return;setBusy(true);setError('');try{const {data:ex}=await supabase.from('opportunities').select('id,name').eq('workspace_id',workspaceId).eq('conversation_id',selected.id).limit(1);if(ex?.length)throw new Error(`Esta conversación ya tiene la oportunidad “${ex[0].name}”.`);const stage=stages.find(s=>s.id===opp.stage_id);const {data:created,error:e2}=await supabase.from('opportunities').insert({workspace_id:workspaceId,name:opp.name.trim(),contact_id:selected.contact_id,conversation_id:selected.id,stage_id:opp.stage_id,owner_id:selected.assigned_user_id||userId,amount:opp.amount?Number(opp.amount):null,currency:'ARS',probability:stage?.probability??null,source_channel:selected.channel_connections?.channel||null,expected_close_date:opp.expected_close_date||null}).select('id,name').single();if(e2)throw e2;await supabase.from('opportunity_history').insert({workspace_id:workspaceId,opportunity_id:created.id,changed_by:userId,field_name:'created',new_value:stage?.name||'Nueva oportunidad'});setOpenOpp(false);setSuccess(`Oportunidad “${created.name}” creada.`)}catch(x:any){setError(x.message||'No pudimos crear la oportunidad')}finally{setBusy(false)}}

 return <AppShell><div className="page inbox-page"><div className="page-head"><div><h1>Inbox</h1><p>Todas las conversaciones del negocio en un solo lugar.</p></div><div style={{display:'flex',gap:8,alignItems:'center'}}><span style={{fontSize:12,display:'flex',gap:5,alignItems:'center',opacity:.7}}><Wifi size={14}/>{live?'En tiempo real':'Conectando...'}</span><button className="secondary compact" onClick={()=>workspaceId&&loadConversations(workspaceId)}><RefreshCw size={15}/> Actualizar</button><button className="primary compact" onClick={()=>setOpenNew(true)}><Plus size={17}/> Conversación de prueba</button></div></div>
 {error&&<div className="error-banner">{error}</div>}{success&&<div className="test-banner"><strong>Listo</strong><span>{success}</span></div>}
 <div style={{display:'flex',gap:10,marginBottom:12,fontSize:13,opacity:.72}}><span><strong>{filtered.length}</strong> conversaciones</span><span>·</span><span><strong>{unreadTotal}</strong> sin leer</span></div>
 <div className="inbox-grid">
  <section className="inbox-list panel"><div className="inbox-list-head" style={{gap:8,flexWrap:'wrap'}}><div className="search local" style={{minWidth:180,flex:1}}><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por cliente o mensaje..."/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="open">Abiertas</option><option value="pending">Pendientes</option><option value="closed">Cerradas</option><option value="all">Todas</option></select><select value={channelFilter} onChange={e=>setChannelFilter(e.target.value)}><option value="all">Todos los canales</option>{channels.map(x=><option key={x} value={x}>{labelChannel(x)}</option>)}</select></div><div className="conversation-list">{filtered.length===0?<div className="mini-empty">No hay conversaciones para este filtro.</div>:filtered.map(c=>{const p=previews[c.id];return <button key={c.id} className={`conversation-item ${selectedId===c.id?'selected':''}`} onClick={()=>setSelectedId(c.id)}><div className="channel-bubble">{channelIcon(c.channel_connections?.channel)}</div><div className="conversation-copy"><div><strong>{contactName(c)}</strong><small>{formatTime(p?.sent_at||c.last_message_at)}</small></div><div style={{display:'flex',gap:5,flexWrap:'wrap',margin:'4px 0'}}><Badge text={labelChannel(c.channel_connections?.channel||'')}/><Badge text={labelStatus(c.status)}/>{c.priority!=='normal'&&<Badge text={labelPriority(c.priority)}/>}</div><p style={{fontWeight:c.unread_count>0?650:400}}>{p?.body||c.subject||'Sin mensajes todavía'}</p></div>{c.unread_count>0&&<b className="unread">{c.unread_count}</b>}</button>})}</div></section>
  <section className="chat panel">{!selected?<div className="empty"><MessageCircle size={28}/><strong>Elegí una conversación</strong><span>Acá vas a responder consultas sin cambiar de plataforma.</span></div>:<><div className="chat-head"><div className="chat-person"><div className="contact-avatar">{selected.contacts?.first_name?.[0]||'?'}</div><div><strong>{contactName(selected)}</strong><span>{labelChannel(selected.channel_connections?.channel||'')} · {selected.channel_connections?.settings?.mode==='test'?'Prueba':'En vivo'}</span></div></div><select value={selected.status} onChange={e=>updateConversation({status:e.target.value})}><option value="open">Abierta</option><option value="pending">Pendiente</option><option value="closed">Cerrada</option></select></div><div className="message-stream">{messages.length===0?<div className="mini-empty">Todavía no hay mensajes.</div>:messages.map(m=><div key={m.id} className={`message-line ${m.direction}`}><div className="message-bubble"><p>{m.body||'Adjunto'}</p><small>{formatTime(m.sent_at)} · {m.status}</small></div></div>)}</div><form className="composer" onSubmit={sendReply}><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Escribí una respuesta..." onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><button className="primary" disabled={busy||!reply.trim()}><Send size={16}/> Enviar</button></form></>}</section>
  <aside className="inbox-side panel">{!selected?<div className="mini-empty">Información del cliente</div>:<><div className="side-profile"><div className="profile-avatar small">{selected.contacts?.first_name?.[0]||'?'}</div><strong>{contactName(selected)}</strong>{selected.contacts&&<Link className="inline-link" href={`/contacts/${selected.contacts.id}`}>Ver Cliente 360°</Link>}</div><div className="side-section"><span className="side-label">Responsable</span><select value={selected.assigned_user_id||''} onChange={e=>updateConversation({assigned_user_id:e.target.value||null})}><option value="">Sin asignar</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.profiles?.full_name||'Usuario'} · {m.role}</option>)}</select></div><div className="side-section"><span className="side-label">Prioridad</span><select value={selected.priority} onChange={e=>updateConversation({priority:e.target.value})}><option value="low">Baja</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div><div className="side-section"><span className="side-label">Estado</span><div className="side-value"><Badge text={labelStatus(selected.status)}/> <Badge text={labelPriority(selected.priority)}/></div></div><div className="side-section"><span className="side-label">Canal</span><div className="side-value">{channelIcon(selected.channel_connections?.channel)} {labelChannel(selected.channel_connections?.channel||'')}</div></div><div className="side-section"><button className="primary" style={{width:'100%',justifyContent:'center'}} onClick={startOpportunity}><BadgeDollarSign size={16}/> Crear oportunidad</button></div></>}</aside>
 </div>
 {openNew&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>Conversación de prueba</h2><p>Simulá un mensaje entrante.</p></div><button className="iconbtn" onClick={()=>setOpenNew(false)}>×</button></div><form className="form-grid" onSubmit={createConversation}><label className="full">Contacto<select value={newConv.contact_id} onChange={e=>setNewConv({...newConv,contact_id:e.target.value})} required><option value="">Elegí un contacto</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name||''}</option>)}</select></label><label className="full">Canal<select value={newConv.channel} onChange={e=>setNewConv({...newConv,channel:e.target.value})}>{channels.map(c=><option key={c} value={c}>{labelChannel(c)}</option>)}</select></label><label className="full">Mensaje<textarea value={newConv.message} onChange={e=>setNewConv({...newConv,message:e.target.value})}/></label><div className="modal-actions full"><button type="button" className="secondary" onClick={()=>setOpenNew(false)}>Cancelar</button><button className="primary" disabled={busy}>Crear</button></div></form></div></div>}
 {openOpp&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>Crear oportunidad</h2><p>Convertí esta conversación en una oportunidad comercial.</p></div><button className="iconbtn" onClick={()=>setOpenOpp(false)}>×</button></div><form className="form-grid" onSubmit={createOpportunity}><label className="full">Nombre<input value={opp.name} onChange={e=>setOpp({...opp,name:e.target.value})} required/></label><label>Monto<input type="number" value={opp.amount} onChange={e=>setOpp({...opp,amount:e.target.value})}/></label><label>Etapa<select value={opp.stage_id} onChange={e=>setOpp({...opp,stage_id:e.target.value})} required>{stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="full">Fecha estimada<input type="date" value={opp.expected_close_date} onChange={e=>setOpp({...opp,expected_close_date:e.target.value})}/></label><div className="modal-actions full"><button type="button" className="secondary" onClick={()=>setOpenOpp(false)}>Cancelar</button><button className="primary" disabled={busy}>Crear oportunidad</button></div></form></div></div>}
 </div></AppShell>
}

function Badge({text}:{text:string}){return <span style={{fontSize:10.5,fontWeight:700,padding:'3px 6px',borderRadius:999,background:'rgba(100,116,139,.10)',whiteSpace:'nowrap'}}>{text}</span>}
function contactName(c:Conversation){return c.contacts?`${c.contacts.first_name} ${c.contacts.last_name||''}`.trim():'Contacto sin identificar'}
function formatTime(v:string|null|undefined){if(!v)return '';const d=new Date(v),now=new Date(),same=d.toDateString()===now.toDateString();return new Intl.DateTimeFormat('es-AR',same?{hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'2-digit'}).format(d)}
function labelStatus(v:string){return v==='open'?'Abierta':v==='pending'?'Pendiente':v==='closed'?'Cerrada':v}
function labelPriority(v:string){return v==='low'?'Baja':v==='normal'?'Normal':v==='high'?'Alta':v==='urgent'?'Urgente':v}
function labelChannel(v:string){return v==='instagram'?'Instagram':v==='facebook'?'Facebook':v==='whatsapp'?'WhatsApp':v==='mercadolibre'?'Mercado Libre':v==='tiktok'?'TikTok':v||'Canal'}
function channelIcon(v?:string){if(v==='instagram')return <Instagram size={16}/>;if(v==='facebook')return <Facebook size={16}/>;if(v==='mercadolibre')return <Store size={16}/>;if(v==='tiktok')return <Music2 size={16}/>;return <MessageCircle size={16}/>}
