'use client'
import { FormEvent,useEffect,useMemo,useState } from 'react'
import { AppShell } from '@/components/AppShell'
import { Plus,Search,Pencil,Power } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import './products.css'

type Product={id:string;workspace_id:string;name:string;sku:string|null;price:number|null;currency:string;active:boolean;created_at:string}
export default function Products(){
 const [workspaceId,setWorkspaceId]=useState<string|null>(null);const [rows,setRows]=useState<Product[]>([]);const [q,setQ]=useState('');const [filter,setFilter]=useState('active');const [open,setOpen]=useState(false);const [edit,setEdit]=useState<Product|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [form,setForm]=useState({name:'',sku:'',price:'',currency:'ARS',active:true})
 useEffect(()=>{load()},[])
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:mem}=await supabase.from('workspace_members').select('workspace_id').eq('user_id',user.id).eq('status','active').limit(1).single();if(!mem)return;setWorkspaceId(mem.workspace_id);const {data,error}=await supabase.from('products').select('id,workspace_id,name,sku,price,currency,active,created_at').eq('workspace_id',mem.workspace_id).order('created_at',{ascending:false});if(error)setError(error.message);else setRows((data||[]) as Product[])}
 const filtered=useMemo(()=>rows.filter(p=>`${p.name} ${p.sku||''}`.toLowerCase().includes(q.toLowerCase())&&(filter==='all'||(filter==='active'?p.active:!p.active))),[rows,q,filter])
 function startCreate(){setEdit(null);setForm({name:'',sku:'',price:'',currency:'ARS',active:true});setOpen(true)}
 function startEdit(p:Product){setEdit(p);setForm({name:p.name,sku:p.sku||'',price:p.price==null?'':String(p.price),currency:p.currency,active:p.active});setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();if(!workspaceId)return;setBusy(true);setError('');const payload={name:form.name.trim(),sku:form.sku.trim()||null,price:form.price===''?null:Number(form.price),currency:form.currency,active:form.active};let error:any;if(edit){({error}=await supabase.from('products').update(payload).eq('id',edit.id).eq('workspace_id',workspaceId))}else{({error}=await supabase.from('products').insert({...payload,workspace_id:workspaceId}))}if(error)setError(error.message);else{setOpen(false);await load()}setBusy(false)}
 async function toggle(p:Product){const {error}=await supabase.from('products').update({active:!p.active}).eq('id',p.id).eq('workspace_id',p.workspace_id);if(error)setError(error.message);else setRows(v=>v.map(x=>x.id===p.id?{...x,active:!x.active}:x))}
 return <AppShell><div className="page"><div className="page-head"><div><h1>Productos</h1><p>Catálogo comercial para usar dentro de oportunidades.</p></div><button className="primary compact" onClick={startCreate}><Plus size={17}/> Nuevo producto</button></div>{error&&<div className="error-banner">{error}</div>}<div className="products-toolbar"><div className="search local"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por producto o SKU..."/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Activos</option><option value="inactive">Inactivos</option><option value="all">Todos</option></select><span className="count">{filtered.length} productos</span></div>{filtered.length===0?<section className="panel"><div className="empty"><strong>{rows.length?'No encontramos coincidencias':'Todavía no hay productos'}</strong><span>{rows.length?'Probá cambiando la búsqueda o el filtro.':'Creá tu catálogo para empezar a asociar productos a oportunidades.'}</span>{!rows.length&&<button className="secondary" onClick={startCreate}>Crear primer producto</button>}</div></section>:<div className="product-grid">{filtered.map(p=><article className={`product-card ${!p.active?'inactive':''}`} key={p.id}><div className="product-card-head"><div><h3>{p.name}</h3><small>{p.sku?`SKU ${p.sku}`:'Sin SKU'}</small></div><span className={`status-pill ${p.active?'':'off'}`}>{p.active?'Activo':'Inactivo'}</span></div><div className="product-price">{p.price==null?'Precio a definir':money(Number(p.price),p.currency)}</div><div className="product-actions"><button className="secondary" onClick={()=>startEdit(p)}><Pencil size={14}/> Editar</button><button className="secondary" onClick={()=>toggle(p)}><Power size={14}/> {p.active?'Desactivar':'Activar'}</button></div></article>)}</div>}
 {open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><h2>{edit?'Editar producto':'Nuevo producto'}</h2><p>Datos que usarás al armar oportunidades.</p><form onSubmit={save}><label>Nombre<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>SKU<input value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} placeholder="Opcional"/></label><div className="form2"><label>Precio<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Moneda<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option value="ARS">ARS</option><option value="USD">USD</option></select></label></div><label className="check-label"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Producto activo</label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Guardando…':'Guardar producto'}</button></div></form></div></div>}</div></AppShell>}
function money(v:number,c:string){return new Intl.NumberFormat('es-AR',{style:'currency',currency:c||'ARS',maximumFractionDigits:2}).format(v)}
