'use client'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { AppShell } from '@/components/AppShell'
import { supabase } from '@/lib/supabase'
import { Building2, Users, KanbanSquare, Plug, Save, Plus, ArrowUp, ArrowDown, Trash2, Instagram, Facebook, MessageCircle, ShoppingBag, Music2, Mail, ShieldCheck } from 'lucide-react'
import './settings.css'

type Workspace={id:string;name:string;slug:string}
type Member={id:string;user_id:string;role:string;status:string;full_name:string|null;email?:string|null}
type Stage={id:string;name:string;position:number;probability:number;is_won:boolean;is_lost:boolean}
type Connection={id:string;channel:string;name:string;external_account_name:string|null;status:string;settings:any}
const roles=['owner','admin','manager','agent']
const channels=['instagram','facebook','whatsapp','mercadolibre','tiktok','email']

export default function SettingsPage(){
 const [tab,setTab]=useState<'business'|'sales'|'team'|'integrations'>('business')
 const [workspace,setWorkspace]=useState<Workspace|null>(null)
 const [currentRole,setCurrentRole]=useState('agent')
 const [members,setMembers]=useState<Member[]>([])
 const [stages,setStages]=useState<Stage[]>([])
 const [connections,setConnections]=useState<Connection[]>([])
 const [name,setName]=useState('')
 const [newStage,setNewStage]=useState({name:'',probability:'10',type:'open'})
 const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [busy,setBusy]=useState(false)
 const canAdmin=['owner','admin'].includes(currentRole); const canStages=['owner','admin','manager'].includes(currentRole)
 useEffect(()=>{load()},[])
 async function load(){
  setError('')
  const {data:{user}}=await supabase.auth.getUser();if(!user)return
  const {data:mem,error:me}=await supabase.from('workspace_members').select('id,workspace_id,role,status').eq('user_id',user.id).eq('status','active').limit(1).single();if(me||!mem){setError(me?.message||'No encontramos tu espacio de trabajo.');return}
  setCurrentRole(mem.role)
  const [{data:w,error:we},{data:m},{data:s},{data:c}]=await Promise.all([
   supabase.from('workspaces').select('id,name,slug').eq('id',mem.workspace_id).single(),
   supabase.from('workspace_members').select('id,user_id,role,status').eq('workspace_id',mem.workspace_id).order('created_at'),
   supabase.from('sales_stages').select('id,name,position,probability,is_won,is_lost').eq('workspace_id',mem.workspace_id).order('position'),
   supabase.from('channel_connections').select('id,channel,name,external_account_name,status,settings').eq('workspace_id',mem.workspace_id).order('created_at')
  ])
  if(we||!w){setError(we?.message||'No pudimos cargar el negocio.');return}
  setWorkspace(w as Workspace);setName(w.name);setStages((s||[]) as Stage[]);setConnections((c||[]) as Connection[])
  const raw=(m||[]) as any[];const ids=raw.map(x=>x.user_id)
  let profiles:any[]=[]
  if(ids.length){const {data:p}=await supabase.from('profiles').select('id,full_name').in('id',ids);profiles=p||[]}
  setMembers(raw.map(x=>({...x,full_name:profiles.find(p=>p.id===x.user_id)?.full_name||null})))
 }
 async function saveBusiness(e:FormEvent){e.preventDefault();if(!workspace||!canAdmin)return;setBusy(true);setError('');setSuccess('');const {error}=await supabase.from('workspaces').update({name:name.trim()}).eq('id',workspace.id);if(error)setError(error.message);else{setWorkspace({...workspace,name:name.trim()});setSuccess('Datos del negocio actualizados.')}setBusy(false)}
 async function changeRole(member:Member,role:string){if(!canAdmin||member.role==='owner')return;setError('');const {error}=await supabase.from('workspace_members').update({role}).eq('id',member.id);if(error)setError(error.message);else setMembers(members.map(m=>m.id===member.id?{...m,role}:m))}
 async function updateStage(stage:Stage,patch:Partial<Stage>){if(!canStages)return;const next={...stage,...patch};setStages(stages.map(s=>s.id===stage.id?next:s));const {error}=await supabase.from('sales_stages').update(patch).eq('id',stage.id);if(error){setError(error.message);await load()}}
 async function moveStage(index:number,dir:-1|1){if(!canStages)return;const other=index+dir;if(other<0||other>=stages.length)return;const a=stages[index],b=stages[other];await Promise.all([supabase.from('sales_stages').update({position:b.position}).eq('id',a.id),supabase.from('sales_stages').update({position:a.position}).eq('id',b.id)]);await load()}
 async function addStage(e:FormEvent){e.preventDefault();if(!workspace||!canStages||!newStage.name.trim())return;setBusy(true);setError('');const max=Math.max(0,...stages.map(s=>s.position));const payload={workspace_id:workspace.id,name:newStage.name.trim(),position:max+10,probability:Number(newStage.probability||0),is_won:newStage.type==='won',is_lost:newStage.type==='lost'};const {error}=await supabase.from('sales_stages').insert(payload);if(error)setError(error.message);else{setNewStage({name:'',probability:'10',type:'open'});await load()}setBusy(false)}
 async function removeStage(stage:Stage){if(!canStages||stage.is_won||stage.is_lost)return;if(!confirm(`¿Eliminar la etapa “${stage.name}”? Las oportunidades vinculadas podrían quedar sin etapa.`))return;const {error}=await supabase.from('sales_stages').delete().eq('id',stage.id);if(error)setError(error.message);else await load()}
 const connectionByChannel=useMemo(()=>Object.fromEntries(channels.map(ch=>[ch,connections.find(c=>c.channel===ch)])),[connections])
 if(!workspace&&!error)return <AppShell><div className="loading">Cargando configuración…</div></AppShell>
 return <AppShell><div className="page settings-page"><div className="page-head"><div><h1>Configuración</h1><p>Administrá tu negocio, equipo, proceso de ventas e integraciones.</p></div></div>
 {error&&<div className="error-banner">{error}</div>}{success&&<div className="success-banner">{success}</div>}
 <div className="settings-tabs"><button className={`settings-tab ${tab==='business'?'active':''}`} onClick={()=>setTab('business')}>Negocio</button><button className={`settings-tab ${tab==='sales'?'active':''}`} onClick={()=>setTab('sales')}>Proceso de ventas</button><button className={`settings-tab ${tab==='team'?'active':''}`} onClick={()=>setTab('team')}>Equipo</button><button className={`settings-tab ${tab==='integrations'?'active':''}`} onClick={()=>setTab('integrations')}>Integraciones</button></div>
 {tab==='business'&&<div className="settings-grid"><section className="settings-card"><div className="settings-card-head"><div><h2>Datos del negocio</h2><p>Información principal de este workspace.</p></div><Building2 size={19}/></div><form className="settings-form" onSubmit={saveBusiness}><label>Nombre del negocio<input value={name} onChange={e=>setName(e.target.value)} disabled={!canAdmin}/></label><label>Identificador<input value={workspace?.slug||''} disabled/><small>El identificador interno no se modifica en esta versión.</small></label><div className="settings-actions"><button className="primary" disabled={!canAdmin||busy}><Save size={15}/>{busy?'Guardando…':'Guardar cambios'}</button></div></form>{!canAdmin&&<div className="permission-note">Tu rol puede ver esta información, pero solo owner/admin pueden modificarla.</div>}</section><aside className="settings-card"><div className="settings-card-head"><div><h2>Resumen</h2><p>Estado actual del workspace.</p></div><ShieldCheck size={19}/></div><div className="settings-kpi"><div><span>Miembros</span><strong>{members.length}</strong></div><div><span>Etapas</span><strong>{stages.length}</strong></div><div><span>Conexiones</span><strong>{connections.filter(c=>['connected','active'].includes(c.status)).length}</strong></div><div><span>Tu rol</span><strong style={{fontSize:16}}>{labelRole(currentRole)}</strong></div></div></aside></div>}
 {tab==='sales'&&<section className="settings-card"><div className="settings-card-head"><div><h2>Etapas del Proceso de ventas</h2><p>Definí el orden, probabilidad y resultado de cada etapa.</p></div><KanbanSquare size={19}/></div><div className="setting-list">{stages.map((s,i)=><div className="stage-row" key={s.id}><div className="stage-order">{i+1}</div><input className="stage-name" value={s.name} disabled={!canStages||s.is_won||s.is_lost} onChange={e=>setStages(stages.map(x=>x.id===s.id?{...x,name:e.target.value}:x))} onBlur={()=>updateStage(s,{name:stages.find(x=>x.id===s.id)?.name||s.name})}/><div className="stage-probability"><select value={s.probability} disabled={!canStages} onChange={e=>updateStage(s,{probability:Number(e.target.value)})}>{[0,10,20,30,40,50,60,70,80,90,100].map(p=><option value={p} key={p}>{p}%</option>)}</select></div><div className="stage-type">{s.is_won?'Resultado: Ganado':s.is_lost?'Resultado: Perdido':'Etapa abierta'}</div><div className="stage-actions"><button className="icon-button" disabled={!canStages||i===0} onClick={()=>moveStage(i,-1)}><ArrowUp size={14}/></button><button className="icon-button" disabled={!canStages||i===stages.length-1} onClick={()=>moveStage(i,1)}><ArrowDown size={14}/></button><button className="icon-button danger-button" disabled={!canStages||s.is_won||s.is_lost} onClick={()=>removeStage(s)}><Trash2 size={14}/></button></div></div>)}</div><form className="mini-form" onSubmit={addStage}><input placeholder="Nueva etapa" value={newStage.name} onChange={e=>setNewStage({...newStage,name:e.target.value})} disabled={!canStages}/><select value={newStage.probability} onChange={e=>setNewStage({...newStage,probability:e.target.value})} disabled={!canStages}>{[0,10,20,30,40,50,60,70,80,90,100].map(p=><option key={p} value={p}>{p}%</option>)}</select><select value={newStage.type} onChange={e=>setNewStage({...newStage,type:e.target.value})} disabled={!canStages}><option value="open">Abierta</option><option value="won">Ganado</option><option value="lost">Perdido</option></select><button className="primary compact" disabled={!canStages||busy}><Plus size={15}/>Agregar</button></form>{!canStages&&<div className="permission-note">Solo owner, admin o manager pueden modificar las etapas.</div>}</section>}
 {tab==='team'&&<section className="settings-card"><div className="settings-card-head"><div><h2>Equipo</h2><p>Miembros activos y permisos dentro de Lumo.</p></div><Users size={19}/></div><div className="setting-list">{members.map(m=><div className="setting-row" key={m.id}><div className="setting-row-main"><div className="setting-icon"><Users size={17}/></div><div><strong>{m.full_name||'Usuario de Lumo'}</strong><span className="role-pill">{labelRole(m.role)}</span></div></div><div className="setting-row-actions">{m.role==='owner'?<span>Owner del workspace</span>:<select value={m.role} onChange={e=>changeRole(m,e.target.value)} disabled={!canAdmin}>{roles.filter(r=>r!=='owner').map(r=><option key={r} value={r}>{labelRole(r)}</option>)}</select>}</div></div>)}</div><div className="permission-note">Las invitaciones por email requieren el flujo de alta de usuarios que construiremos junto con la versión multiusuario. En esta versión no se simulan invitaciones.</div></section>}
 {tab==='integrations'&&<section className="settings-card"><div className="settings-card-head"><div><h2>Canales e integraciones</h2><p>Estado de las conexiones omnicanal de este negocio.</p></div><Plug size={19}/></div><div className="channel-grid">{channels.map(ch=>{const c=connectionByChannel[ch];return <div className="channel-card" key={ch}><div className="channel-top"><div className="channel-name"><div className="setting-icon">{channelIcon(ch)}</div><div><strong>{labelChannel(ch)}</strong><span>{c?.external_account_name||c?.name||'Sin cuenta conectada'}</span></div></div><span className={`channel-status ${c?.status||''}`}>{c?labelConnection(c.status,c.settings):'No conectado'}</span></div><div className="integration-note">{c?.settings?.mode==='test'?'Conexión utilizada únicamente para las conversaciones de prueba del Inbox.':integrationDescription(ch)}</div><div className="channel-actions"><button className="secondary" disabled>{c&&c.settings?.mode!=='test'?'Administrar':'Conectar'}</button></div></div>})}</div><div className="permission-note">Los botones de conexión real quedan deshabilitados a propósito hasta implementar OAuth/API de cada proveedor. Lumo no mostrará una integración como activa si todavía no existe conexión externa real.</div></section>}
 </div></AppShell>
}
function labelRole(v:string){return ({owner:'Owner',admin:'Administrador',manager:'Manager',agent:'Agente'} as Record<string,string>)[v]||v}
function labelChannel(v:string){return ({instagram:'Instagram',facebook:'Facebook',whatsapp:'WhatsApp',mercadolibre:'Mercado Libre',tiktok:'TikTok',email:'Email'} as Record<string,string>)[v]||v}
function labelConnection(status:string,settings:any){if(settings?.mode==='test')return 'Modo prueba';return ({connected:'Conectado',active:'Conectado',pending:'Pendiente',error:'Error',disconnected:'Desconectado'} as Record<string,string>)[status]||status}
function integrationDescription(v:string){return ({instagram:'Mensajes y conversaciones de Instagram.',facebook:'Mensajes de páginas de Facebook.',whatsapp:'Conversaciones comerciales de WhatsApp.',mercadolibre:'Preguntas y mensajería de Mercado Libre.',tiktok:'Mensajes y leads provenientes de TikTok.',email:'Bandeja de correo conectada al Inbox.'} as Record<string,string>)[v]||''}
function channelIcon(v:string){if(v==='instagram')return <Instagram size={17}/>;if(v==='facebook')return <Facebook size={17}/>;if(v==='whatsapp')return <MessageCircle size={17}/>;if(v==='mercadolibre')return <ShoppingBag size={17}/>;if(v==='tiktok')return <Music2 size={17}/>;return <Mail size={17}/>}